---
- name: installation Mysqls
  apt:
    name: mariadb-server-10.1,python-mysqldb
    state: latest
  become: yes

- name: Install python-selinux
  apt: name=python-selinux state=present
  become: yes

- name: Make sure a service is running
  systemd:
    state: started
    enabled: yes
    name: mariadb
