---
# tasks file for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - apache2
    - mariadb-server
    - php7.3
    - libapache2-mod-php7.3
    - python-mysqldb
    - php7.3-mysql 
    - php7.3-curl 
    - php7.3-json 
    - php7.3-gd 
    - php7.3-intl 
    - php7.3-sqlite3 
    - php7.3-gmp 
    - php7.3-mbstring 
    - php7.3-xml 
    - php7.3-zip