---
- name: installation apache
  apt:
    name: apache2,php,php-mysql
    state: latest
  become: yes

- name: Install libselinux-dev
  yum: name=libselinux-dev state=present
  become: yes

- name: Make sure a service is running
  systemd:
    state: started
    enabled: yes
    name: apache2
  become: yes
