---
- name: installation apache
  apt:
    name: apache2,php,php-mysql
    state: latest
  become: yes

- name: Install libselinux-dev
  yum: name=libselinux-dev state=present
  become: yes

- name: Make sure a service is running
  systemd:
    state: started
    enabled: yes
    name: apache2
  become: yes

- name: WordPress Default page
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^DocumentRoot /var/www/html/'
    line: DocumentRoot /var/www/html/wordpress/
  become: yes

- name: stop apache2
  systemd:
    state: stopped
    enabled: yes
    name: apache2
  become: yes   

- name: Start apache2
  systemd:
    state: started
    enabled: yes
    name: apache2
  become: yes  