---
- hosts: all
  connection: local

tasks:
- name: Create VM 
  proxmox_kvm: 
    node: prox6node01
    api_user: ansible@pve
    api_password: Pr0jet0penSource!
    api_host: 91.121.112.154:8006
    password: 123456
    hostname: example
    ostemplate: 'local:/var/lib/vz/template/iso/debian-10.2.0-amd64-netinst.iso'
    netif: '{"net0":"name=eth0,ip=192.168.0.67/24,gw=192.168.0.1,bridge=vmbr0"}'
    vmid: 200
    storage: local-lvm
    state: present
    nameserver: 'test'
    cpus: 1
    cores: 2
    memory: 2048
    disk: 10
    
- name: Start VM
  promox: 
    api_host: node1
    api_user: ansible@pve
    api_password: Pr0jet0penSource!
    vmid: 200
    state: started