---
- hosts: all
  connection: local

  tasks:
  - name: Clone VM Template
    command: 
      cmd: sudo qm clone "{{ template }}" "{{ vmid }}" --name "{{ name }}"

  - name: Definition de la mémoire
    command:
      cmd: sudo qm set "{{ vmid }}" --memory "{{ memory }}"

  - name: Taille du HDD
    command: 
      cmd: sudo qm resize "{{ vmid }}" scsi0 "{{ taille }}"G

  - name: Configuration CPU
    command:
      cmd: sudo qm set "{{ vmid }}" --cores "{{ cores }}" 

  - name: Configuration réseau 
    command:
      cmd: sudo qm set "{{ vmid }}" --ipconfig0 ip="{{ ip }}"/24,gw=192.168.10.254
  
  - name: Lancement de la VM
    command:
      cmd: sudo qm start "{{ vmid }}" 
