---
- name: Create WordPress database
  mysql_db: name={{ wp_db_nom }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_nom }}.*:ALL host='%' state=present


